---

- name: Configure kubeadm on master node
  hosts: master
  gather_facts: True
  tasks:
  #- name: Initilize kubernetes cluster
    #shell: "sudo kubeadm init --upload-certs --control-plane-endpoint {{ ansible_facts['hostname'] }}:6443 --pod-network-cidr 192.168.0.0/16"
    #become: True
    #become_method: sudo

  - name: Create directory for Kuberenetes config
    file:
      path: ~/.kube
      state: directory

  - name: Get home directory for ssh user
    debug:
      var: ansible_env['HOME']
    register: user_home

  - name: Copy Kuberentes admin config
    copy:
      remote_src: True
      src: /etc/kubernetes/admin.conf
      dest: "{{ ansible_env['HOME'] }}/.kube/config"
    become: True
    become_method: sudo
  - name: Bebgg
    debug:
      var: "{{ ansible_facts['real_user_id'] }}"

  - name: Set ownership of config file
    file:
      path: "{{ ansible_env['HOME'] }}/.kube/config"
      state: file
      owner: "{{ ansible_facts['real_user_id'] }}"
      group: "{{ ansible_facts['real_group_id'] }}"
    become: True

  - name: Install pip
    apt:
      name: python3-pip
      state: present
    become: True

  - name: Install pre-requisites
    pip:
      name:
        - pyyaml
        - kubernetes
      break_system_packages: True

  - name: Get join command
    shell: sudo kubeadm token create --print-join-command
    register: join_command

  - name: Add dummy host for variables
    add_host:
      name: "variable_host"
      join_cmd: "{{ join_command.stdout }}"

  - name: Create a CNI Callico deployment # https://stackoverflow.com/a/79229320
    kubernetes.core.k8s:
      state: present
      src: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml

- name: Configure worker nodes
  hosts: workers
  gather_facts: True
  become: False
  tasks:
  - name: Join the cluster
    shell: "sudo {{ hostvars['variable_host']['join_cmd'] }}"

- name: Configure lables on worker nodes
  hosts: all
  gather_facts: True
  tasks:
  - name: Set labels
    kubernetes.core.k8s:
      state: patched
      kind: Node
      name: "{{ hostvars[item]['ansible_hostname'] }}"
      definition:
        metadata:
          labels:
            node-role.kubernetes.io/worker: worker
    loop: "{{ groups['workers'] }}"
    when: "'master' in {{ group_names }}"

- name: Kubernetes management
  hosts: master
  gather_facts: False
  tasks:
  - name: Set labels



  ####### Kuberenetes maganemnt parts
  #
