apiVersion: v1
kind: ConfigMap
metadata:
  name: influx-files
  namespace: monitoring
data:
  setup_dbrp: |
    #!/bin/bash
    # 

    # Create the DBRP policy 
    # This isn't _strictly_ necessary as more
    # recent versions auto-map, but as we're here
    # anyway lets be explicit
    influx v1 dbrp create \
    --bucket-id "${DOCKER_INFLUXDB_INIT_BUCKET_ID}" \
    --db telegraf \
    --rp autogen \
    --default \
    --org "${DOCKER_INFLUXDB_INIT_ORG}"

    # Create the write user
    influx v1 auth create \
      --username ${V1_WRITE_USERNAME} \
      --password ${V1_WRITE_PASSWORD} \
      --write-bucket ${DOCKER_INFLUXDB_INIT_BUCKET_ID} \
      --org ${DOCKER_INFLUXDB_INIT_ORG}

    influx v1 auth create \
      --username ${V1_READ_USERNAME} \
      --password ${V1_READ_PASSWORD} \
      --read-bucket ${DOCKER_INFLUXDB_INIT_BUCKET_ID} \
      --org ${DOCKER_INFLUXDB_INIT_ORG}

